<?
$PERM["seller-account"]["7"]="W";
$PERM["seller-account"]["*"]="D";
$PERM["buyer-account"]["6"]="W";
$PERM["buyer-account"]["*"]="D";
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>